---
# file: roles/shorewall/tasks/centos_6.5.yml

- name: ###### STARTING CENTOS_6.5.YML #######
  debug:
    var="{{ ansible_lsb.major_release }}"

- debug: var=ansible_hostname 

- name: ensure for directories
  file:
    path='{{ item.path }}'
    state=directory
    mode=0755
  with_items:
    - { path: '{{ shorewall_rpm_directory }}' }

- name: "add shorewall rpm key"
  rpm_key:
    state=present
    key="{{ shorewall_gpg_key_url }}"

- name: "download latest shorewall packages"
  command: "wget -r --no-directories --no-parent --reject 'index.html*' http://www.invoca.ch/pub/packages/shorewall/RPMS/ils-6/noarch/"
  args:
    chdir: '{{ shorewall_rpm_directory }}/'
    creates: '{{ shorewall_rpm_directory }}/shorewall*'


#- name: "CentOS 6.5: install shorewall rpms"
#  yum:
#    pkg="{{ shorewall_core_package_download_url }}"
#    state=present


# could everything below go into an os neutral file?

# zones

- name: template our shorewall configuration  files
  template:
    backup=yes
    src='{{ ansible_distribution }}/{{ ansible_lsb.major_release }}/{{ item.value.src }}.j2'
    dest='{{ item.value.dest }}'
    owner='{{ item.value.owner }}'
    group='{{ item.value.group }}'
    mode='{{ item.value.mode }}'
  with_dict: "{{ shorewall_config_files }}"
  notify:
   - restart shorewall
  tags: [ 'packages', 'shorewall' ]

- name: "ensure masq file templatized when shorewall_configure_masq == true"
  template:
    src='{{ ansible_distribution }}/{{ ansible_lsb.major_release }}/masq.j2'
    dest='/etc/shorewall/masq'
    owner='{{ item.value.owner }}'
    group='{{ item.value.group }}'
    mode='{{ item.value.mode }}'
  when: shorewall_configure_masq is defined and shorewall_configure_masq == True
  notify: 
  - restart shorewall
  tags: [ 'packages', 'shorewall' ]

# - name: shorewall configuration check
# if not correctly configured roll it back

- name: enable shorewall
  service: name=shorewall state=started enabled=yes
  tags: [ 'packages', 'shorewall' ]

