---
# file: role/shorewall/tasks/centos.yml

- debug:
    var="{{ ansible_lsb.major_release }}"

- name: "run tasks/centos_6yml when ansible_lsb.major_release is 6"
  include: centos_6.yml
  when: ansible_lsb.major_release == "6"

