---
# tasks file for shorewall

- name: "run tasks/ubuntu.yml when ansible_distribution is Ubuntu"
  include: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

#- name: Running debian.yml
#  include: debian.yml
#  when: ansible_distribution == "Debian"

#- name: running darwin.yml
#  include: darwin.yml
#  when: ansible_os_family == "Darwin"

- name: "run tasks/centos.yml when ansible_distribution is CentOS"
  include: centos.yml
  when: ansible_distribution == 'CentOS'


